slstatus &

#dwmblocks &

#exec $HOME/.config/polybar/./launch.sh &

xwallpaper --zoom /home/aleksa/.config/wall.png &
#/home/aleksa/.config/scr/wallpaper_scr/./LiveWallpaper.sh

xrdb /home/aleksa/.config/Xresources &

#xrdb /home/aleksa/.config/xthemes/.Xresources &

exec xcompmgr &
exec dwm
#/home/aleksa/.config/WallSoft/foo-Wallpaper-Feh-Gif/./back4.sh /home/aleksa/Pix/live_wallpapers/cherry_train.gif

